AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - SamPolicyTemplateTranslator
Parameters:
  Administrator:
    Type: String
    Default: "Alice"
  User:
    Type: String
    Default: "Bob"
Resources:
  Key:
    Type: AWS::KMS::Key
    Properties:
      Description: A key with a sane default policy
      KeyPolicy:
        DefaultKeyPolicy:
          Administrator: 
            Ref: Administrator
          User: 
            Ref: User
