Description: A multi-stage application delivery pipeline. Stages can be deployed to separate accounts. Automated test actions after deployments can be used to stop the pipeline if any tests fail. Apache-2.0 License. Adapt this template to your needs and thoruoughly test it before introducing it in a production environment. **WARNING** This template will create resources in your account that may incur billing charges.

Parameters:

  AppName:
    Type: String
    Description: The unique name for this application. The name will be used as a part of resource names and tags.

  TeamName:
    Type: String
    Description: The name of the team that owns this application.
  
  StageNames:
    Type: CommaDelimitedList
    Description: A list of stage names, for example, "dev,stage,prod"
    Default: prod

  Accounts:
    Type: CommaDelimitedList
    Description: A list of accounts to match the stage names. If left blank, the assumption is that this is a single-account pipeline that is being deployed to the currently configured AWS account. This template does not bootstrap those accounts. Bootstrapping has to be done prior to deploying this template.
    Default: ""

  PipelineSourceKey:
    Type: String
    Description: The name of the S3 object key for the pipeline source
    Default: pipeline-source.zip

  AppSourceKey:
    Type: String
    Description: The name of the S3 object key for the application source
    Default: application-source.zip

  # Note: For each new parameter added here, also add it to the SelfMutate action

Constants:
  S3Arn: "arn:${AWS::Partition}:s3:::"
  PipelineSourceArn: ${Constant:S3Arn}${PipelineSource.BucketName}
  AppSourceArn: ${Constant:S3Arn}${AppSource.BucketName}
  ArtifactArn: ${Constant:S3Arn}${Artifacts.BucketName}

Resources:

  PipelineSource:
    Type: LocalModule
    Source: ../../../modules/bucket.yaml
    Properties:
      Name: !Sub ${AppName}-pipeline-source
      EnableEventBridge: true

  AppSource:
    Type: LocalModule
    Source: ../../../modules/bucket.yaml
    Properties:
      Name: !Sub ${AppName}-app-source

  Artifacts:
    Type: LocalModule
    Source: ../../../modules/bucket.yaml
    Properties:
      Name: !Sub ${AppName}-artifacts

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref AppName
      RoleArn: !GetAtt PipelineRole.Arn
      RestartExecutionOnUpdate: true
      ArtifactStore:
        Type: S3
        Location: !Sub ${Artifacts.BucketName}
      Stages:
        - Name: Source
          Actions:
            - Name: PipelineSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                S3Bucket: !Sub ${PipelineSource.BucketName}
                S3ObjectKey: !Ref PipelineSourceKey
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: pipeline-source
            - Name: AppSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                S3Bucket: !Sub ${AppSource.BucketName}
                S3ObjectKey: !Ref AppSourceKey
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: application-source
        - Name: SelfMutate
          Actions:
            - Name: StackUpdate
              InputArtifacts:
                - Name: pipeline-source
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CreateUpdate
                StackName: ${AWS::StackName}
                Capabilities:
                  - CAPABILITY_IAM
                TemplatePath: SourceArtifact::multi-stage.yaml
                ParameterOverrides:
                  AppName: !Ref AppName
                  TeamName: !Ref TeamName
                  StageNames: !Ref StageNames
                  Accounts: !Ref Accounts
                  PipelineSourceKey: !Ref PipelineSourceKey
                  AppSourceKey: !Ref AppSourceKey
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Validate
              InputArtifacts:
                - Name: pipeline-source
                - Name: app-source
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref Validate
                PrimarySource: pipeline-source
                EnvironmentVariables: |-
                  [
                    {
                      "name": "MY_VAR",
                      "type": "PLAINTEXT",
                      "value": "abc"
                    }
                  ]
              RunOrder: 1
            - Name: Build
              InputArtifacts:
                - Name: application-source
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref Build
                EnvironmentVariables: |-
                  [
                    {
                      "name": "MY_VAR",
                      "type": "PLAINTEXT",
                      "value": "abc"
                    }
                  ]
              RunOrder: 2

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: '2012-10-17'

  PipelinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AppName}-pipeline-policy"
      Roles:
        - !Ref PipelineRole
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - !Sub ${Constant::ArtifactArn}
              - !Sub ${Constant::ArtifactArn}/*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - !Sub ${Constant::AppSourceArn}
              - !Sub ${Constant::AppSourceArn}/*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - !Sub ${Constant::PipelineSourceArn}
              - !Sub ${Constant::PipelineSourceArn}/*
          - Action:
              - codebuild:StartBuild
              - codebuild:BatchGetBuilds
              - codebuild:StopBuild
              - codebuild:RetryBuild
              - codebuild:StartBuildBatch
              - codebuild:RetryBuildBatch
              - codebuild:StopBuildBatch
            Effect: Allow
            Resource:
              - !GetAtt ValidateProject.Arn
              - !GetAtt BuildProject.Arn

  Validate:
    Type: LocalModule
    Description: Build project to validate compliance
    Source: ../../../modules/build-project.yaml
    Properties:
      Name: !Sub ${AppName}-validate
      ArtifactBucket: !Sub ${Artifacts.BucketName}

  Build:
    Type: LocalModule
    Description: Build project for the application source
    Source: ../../../modules/build-project.yaml
    Properties:
      Name: !Sub ${AppName}-build
      ArtifactBucket: !Sub ${Artifacts::BucketName}

  Event:
    Type: LocalModule
    Source: ../../../modules/pipeline-events.yaml
    Properties:
      PipelineName: !Ref Pipeline
    Overrides:
      Rule:
        Properties:
          EventPattern:
            detail:
              bucket:
                name:
                  - !Ref PipelineSource.BucketName
                  - !Ref AppSource.BucketName

Outputs:

  AppSourceBucket:
    Value: !Sub ${AppSource.BucketName}

