Description: This module creates an S3 bucket that will pass common compliance checks. It can create an associated log bucket and replica bucket, and encrypts the contents of the bucket.

Parameters:

  AppName:
    Type: String
    Description: This string will serve as a prefix for all resource names, which have the general form of AppName-ResourceName-Region-Account. 

  CreateLogBucket:
    Type: Boolean
    Description: If true, create a bucket for access logs
    Default: false

  CreateReplicaBucket:
    Type: Boolean
    Description: If true, create a bucket for replicas
    Default: false

Conditions:

  IsLoggingEnabled:
    Fn::Equals:
      - CreateLoggingBucket
      - true

  IsReplicationEnabled:
    Fn::Equals:
      - CreateReplicaBucket
      - true

Constants:
  S3Arn: "arn:${AWS::Partition}:s3:::"
  BucketName: "${AppName}-${AWS::Region}-${AWS::AccountId}"
  LogBucketName: "${AppName}-logs-${AWS::Region}-${AWS::AccountId}"
  LogBucketArn: "${Constant::S3Arn}${Constant::LogBucketName}"
  ReplicaBucketName: "${AppName}-replicas-${AWS::Region}-${AWS::AccountId}"

Resources:

  LogBucket:
    Type: AWS::S3::Bucket
    Condition: IsLoggingEnabled
    Metadata:
      Comment: This bucket records access logs for the main bucket
      checkov:
        skip:
          - comment: This is the log bucket
            id: CKV_AWS_18
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_REPLICATION_ENABLED
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${Constant::LogBucketName}
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: COMPLIANCE
            Years: 1
      ObjectLockEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  LogBucketAccess:
    Condition: IsLoggingEnabled
    Type: LocalModule
    Source: bucket-policy.yaml
    Properties:
      PolicyBucketName: !Sub ${Constant::LogBucketName}
    Overrides:
      Policy:
        Properties:
          PolicyDocument:
            Statement:
              - Action: s3:*
                Condition:
                  Bool:
                    aws:SecureTransport: false
                Effect: Deny
                Principal:
                  AWS: '*'
                Resource:
                  - !Sub ${Constant::LogBucketArn}
                  - !Sub ${Constant::LogBucketArn}/*
              - Action: s3:PutObject
                Condition:
                  ArnLike:
                    aws:SourceArn: !Sub ${Constant::LogBucketArn}/*
                  StringEquals:
                    aws:SourceAccount: !Ref AWS::AccountId
                Effect: Allow
                Principal:
                  Service: logging.s3.amazonaws.com
                Resource:
                  - !Sub ${Constant::LogBucketArn}/*

  Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      guard:
        SuppressedRules:
          - S3_BUCKET_DEFAULT_LOCK_ENABLED
      Rain:
        Content: !Ref Content
        EmptyOnDelete: !Ref EmptyOnDelete
        DistributionLogicalId: NONE
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${Constant::BucketName}
      LoggingConfiguration:
        Fn::If:
          - IsLoggingEnabled
          - DestinationBucketName: !Ref LogBucket
          - !Ref AWS::NoValue
      ObjectLockEnabled: false
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ReplicationConfiguration:
        Fn:If:
          - IsReplicationEnabled
          - Role: !GetAtt ReplicationRole.Arn
            Rules:
              - Destination:
                  Bucket: !GetAtt ReplicaBucket.Arn
                Status: Enabled
          - !Ref AWS::NoValue
      VersioningConfiguration:
        Status: Enabled

  BucketAccess:
    Type: LocalModule 
    Source: bucket-policy.yaml
    Properties:
      PolicyBucketName: !Sub ${Constant::BucketName}

  ReplicaBucket:
    Condition: IsReplicationEnabled
    Type: AWS::S3::Bucket
    Metadata:
      Comment: This bucket is used as a target for replicas from the main bucket
      checkov:
        skip:
          - comment: This is the replica bucket
            id: CKV_AWS_18
      guard:
        SuppressedRules:
          - S3_BUCKET_DEFAULT_LOCK_ENABLED
          - S3_BUCKET_REPLICATION_ENABLED
          - S3_BUCKET_LOGGING_ENABLED
      Rain:
        Content: RAIN_NO_CONTENT
        EmptyOnDelete: !Ref EmptyOnDelete
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${Constant:ReplicaBucketName}
      ObjectLockEnabled: false
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  ReplicaBucketAccess:
    Condition: IsReplicationEnabled
    Type: LocalModule
    Source: bucket-policy.yaml
    Properties:
      PolicyBucketName: !Sub ${Constant::ReplicaBucketName}

  ReplicationPolicy:
    Condition: IsReplicationEnabled
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetReplicationConfiguration
              - s3:ListBucket
            Effect: Allow
            Resource: !Sub arn:${AWS::Partition}:s3:::${Constant::BucketName}
          - Action:
              - s3:GetObjectVersionForReplication
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTagging
            Effect: Allow
            Resource: !Sub arn:${AWS::Partition}:s3:::${Constant::BucketName}/*
          - Action:
              - s3:ReplicateObject
              - s3:ReplicateDelete
              - s3:ReplicationTags
            Effect: Allow
            Resource: !Sub arn:${AWS::Partition}:s3:::${Constant::ReplicaBucketName}/*
        Version: "2012-10-17"
      PolicyName: bucket-replication-policy
      RoleName: !Ref ReplicationRole

  ReplicationRole:
    Condition: IsReplicationEnabled
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
        Version: "2012-10-17"
      Path: /


