Parameters:

  Name:
    Type: String

  ArtifactBucket:
    Type: String

Resources:

  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref Name 
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ComputeType: BUILD_GENERAL1_LARGE
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt Role.Arn
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 480

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyName: !Sub ${Name}
          PolicyDocument:
            Statement:
              - Action:
                  - logs:*
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${Name}:*
              - Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - codebuild:StopBuild
                  - codebuild:RetryBuild
                  - codebuild:StartBuildBatch
                  - codebuild:RetryBuildBatch
                  - codebuild:StopBuildBatch
                Effect: Allow
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${Name}
              - Action:
                  - s3:Get*
                  - s3:List*
                Effect: Allow
                Resource: 
                  - !Sub "arn:${AWS::Partition}:s3:::${ArtifactBucket}"
                  - !Sub "arn:${AWS::Partition}:s3:::${ArtifactBucket}/*"
              - Action:
                  - ec2:DescribeSecurityGroups
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeDhcpOptions
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeVpcs
                Effect: Allow
                Resource: "*"
              - Action:
                  - ec2:CreateNetworkInterfacePermission
                Effect: Allow
                Resource: !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*
            Version: 2012-10-17

Outputs:
  ProjectName:
    Value: !Ref Project
  RoleArn:
    Value: !GetAtt Role.Arn

